Ensure JNI native libraries load when CompiledExpression loads (#8997)
`CompiledExpression` was missing a static block to ensure the native libraries were loaded before the class becomes available for use. This could result in exceptions like the following if no other cudf class with native dependencies is used first in an application:
```
java.lang.UnsatisfiedLinkError: ai.rapids.cudf.ast.CompiledExpression.compile([B)J
  at ai.rapids.cudf.ast.CompiledExpression.compile(Native Method)
  at ai.rapids.cudf.ast.CompiledExpression.<init>(CompiledExpression.java:65)
  at ai.rapids.cudf.ast.Expression.compile(Expression.java:29)
```

Authors:
  - Jason Lowe (https://github.com/jlowe)

Approvers:
  - Robert (Bobby) Evans (https://github.com/revans2)

URL: https://github.com/rapidsai/cudf/pull/8997