Add ability to construct `ListColumn` when size is `None` (#11745)
This PR adds ability to construct a `ListColumn` when `size` is `None`:

```python
In [1]: from cudf.core.column import build_list_column
In [2]: from cudf.core.column import as_column
In [3]: build_list_column(indices = as_column([0, 3]), elements = as_column([0, 2, 4]))
...
TypeError: an integer is required
```

Authors:
  - GALI PREM SAGAR (https://github.com/galipremsagar)

Approvers:
  - Ashwin Srinath (https://github.com/shwina)

URL: https://github.com/rapidsai/cudf/pull/11745