Fix `Series` inputs handling in `Dataframe` constructor (#8065)
Fixes: #8033 

Though we see an error when a Series of `ListDtype` is passed to `DataFrame` constructor, the issues is actually a broader one where we cannot pass a `Series` of string dtype and any series that has nulls to `DataFrame` constructor. For examples:

```python
>>> import cudf
>>> s = cudf.Series(['a', 'b', 'c'])
>>> cudf.DataFrame(s)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nvme/0/pgali/envs/cudfdev/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/nvme/0/pgali/envs/cudfdev/lib/python3.8/site-packages/cudf/core/dataframe.py", line 258, in __init__
    elif hasattr(data, "__cuda_array_interface__"):
  File "/nvme/0/pgali/envs/cudfdev/lib/python3.8/site-packages/cudf/core/series.py", line 6364, in __cuda_array_interface__
    return self._column.__cuda_array_interface__
  File "/nvme/0/pgali/envs/cudfdev/lib/python3.8/site-packages/cudf/core/column/string.py", line 5123, in __cuda_array_interface__
    raise NotImplementedError(
NotImplementedError: Strings are not yet supported via `__cuda_array_interface__`
>>> s = cudf.Series([1, 2, None])
>>> cudf.DataFrame(s)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nvme/0/pgali/envs/cudfdev/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/nvme/0/pgali/envs/cudfdev/lib/python3.8/site-packages/cudf/core/dataframe.py", line 272, in __init__
    new_df = self._from_arrays(data, index=index, columns=columns)
  File "/nvme/0/pgali/envs/cudfdev/lib/python3.8/site-packages/cudf/core/dataframe.py", line 5795, in _from_arrays
    data = cupy.asarray(data)
  File "/nvme/0/pgali/envs/cudfdev/lib/python3.8/site-packages/cupy/_creation/from_data.py", line 66, in asarray
    return core.array(a, dtype, False, order)
  File "cupy/core/core.pyx", line 2016, in cupy.core.core.array
  File "cupy/core/core.pyx", line 2046, in cupy.core.core.array
  File "cupy/core/core.pyx", line 2366, in cupy.core.core._convert_object_with_cuda_array_interface
ValueError: CuPy currently does not support masked arrays.

```

In this PR, we are introducing a special case handling for inputs that are of type `Series`.

Authors:
  - GALI PREM SAGAR (https://github.com/galipremsagar)

Approvers:
  - Keith Kraus (https://github.com/kkraus14)

URL: https://github.com/rapidsai/cudf/pull/8065